import { Employee } from "../data/model";

export const emptyUser: Employee = {
  // name: "Александр",
  // surname: "Вохмин",
  // patronymic: "Сергеевич",
  // inipa: "123-456-789 00",
  // tin: "3664069397",
  // birthDate: "10-05-1990",
  // phoneNumber: "+7(930)686-62-17",
  // specialty: 3,
  // email: "alexs11s@gmail.ru",
  // password: "123456",
  // repeatedPassword: "123456",
name: "",
surname: "",
patronymic: "",
inipa: "",
tin: "",
birthDate: "",
phoneNumber: "",
specialty: 0,
email: "",
password: "",
repeatedPassword: "",
};


// name: "",
// surname: "",
// patronymic: "",
// inipa: "",
// tin: "",
// birthDate: "",
// phoneNumber: "",
// specialty: 0,
// email: "",
// password: "",
// repeatedPassword: "",